version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    links:
      - portfolio
      - post_social
  portfolio:
    container_name: portfolio
    restart: always
    image: fr4nca/portfolio
    expose:
      - '3000'
  post_social:
    container_name: post_social
    restart: always
    image: fr4nca/post_social
    expose:
      - '3001'
